### ISSUE TITLE
Blender 4.3

### ISSUE THREAD

**Issue by Chem-pro** [NSACloud/RE-Chain-Editor#6]
not working with Blender 4.3 with this error
" The issue in your script occurs because Material objects no longer have the shadow_method attribute in Blender 4.3. Instead, material shadow settings are now typically configured differently, depending on the render engine (e.g., Eevee or Cycles).
To fix the problem, you need to adjust the code in re_chain_geoNodes.py "

Python: Traceback (most recent call last):
  File "C:\Users\????\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RE-Chain-Editor-main\__init__.py", line 135, in execute
    success = importChainFile(self.filepath,options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\????\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RE-Chain-Editor-main\modules\blender_re_chain.py", line 578, in importChainFile
    nodeGroup = getConeGeoNodeTree()
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\????\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RE-Chain-Editor-main\modules\re_chain_geoNodes.py", line 667, in getConeGeoNodeTree
    mat = getConeMat()
          ^^^^^^^^^^^^
  File "C:\Users\????\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\RE-Chain-Editor-main\modules\re_chain_geoNodes.py", line 49, in getConeMat
    mat.shadow_method = "NONE"
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Material' object has no attribute 'shadow_method'
